In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,1,1,0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [4]:
def derivative_sigmoid(z):
    return sigmoid(z)*(1 - sigmoid(z))

In [5]:
#one hidden layer weights
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1
alpha = 1

In [6]:
for i in range(100000):
    #forward propagation with one hidden layer
    output_0 = X
    input_1 = np.dot(output_0, wh) + bh
    output_1 = sigmoid(input_1)
    input_2 = np.dot(output_1, wo) + bo
    output_2 = sigmoid(input_2)

    #backward propagation with one hidden layer
    first_term_output_2 = output_2 - Y
    second_term_output_2 = derivative_sigmoid(input_2)
    first_two_2 = first_term_output_2 * second_term_output_2

    first_term_output_1 = np.dot(first_two_2, wo.T)
    second_term_output_1 = derivative_sigmoid(input_1)
    first_two_1 = first_term_output_1 * second_term_output_1

    derivative_2_w = np.dot(output_1.T, first_two_2)  
    wo = wo - alpha * derivative_2_w 

    derivative_2_b = first_two_2.sum(axis = 0, keepdims = True) 
    bo = bo - alpha * derivative_2_b  

    derivative_1_w = np.dot(output_0.T, first_two_1)
    wh = wh - alpha * derivative_1_w 

    derivative_1_b = first_two_1.sum(axis = 0, keepdims = True)
    bh = bh - alpha * derivative_1_b
    
output_0 = X
input_1 = np.dot(output_0, wh) + bh
output_1 = sigmoid(input_1)
input_2 = np.dot(output_1, wo) + bo
output_2 = sigmoid(input_2)

print('Final Output:')
print(output_2)
print('---------------------------------------')
print('Trained Weights of hidden layer:')
print(wh)
print('Trained Biases of hidden layer:')
print(bh)
print('---------------------------------------')
print('Trained Weights of output layer:')
print(wo)
print('Trained Bias of output layer:')
print(bo)

Final Output:
[[0.00393228]
 [0.99669621]
 [0.99669572]
 [0.00335984]]
---------------------------------------
Trained Weights of hidden layer:
[[7.31443784 5.56152416]
 [7.31665502 5.56210452]]
Trained Biases of hidden layer:
[[-3.3504131 -8.5131016]]
---------------------------------------
Trained Weights of output layer:
[[ 12.55577813]
 [-13.19407815]]
Trained Bias of output layer:
[[-5.95735662]]
